// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/05e9c858cf55270a48b1234e613fa9b26da8be23/angular-ui-router-uib-modal/index.d.ts
declare module 'angular-ui-router-uib-modal' {
// Type definitions for angular-ui-uib-modal (ui.router module) 0.11
// Project: https://github.com/nonplus/angular-ui-router-uib-modal
// Definitions by: Stepan Riha <https://github.com/nonplus>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import * as auir from 'angular-ui-router';

module 'angular' {
	namespace ui {
		interface IState {
			modal?: boolean | string[];
		}
	}
}
}
