// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/3e0607feb4906d6bd1ffd51fb78839bd8a40f994/angular-deferred-bootstrap/index.d.ts
declare var deferredBootstrapper: angular.IDeferredBootstrapperStatic;

declare module angular {
	interface IDeferredBootstrapperStatic {
		bootstrap(configParam: IConfigParam): ng.IPromise<boolean>
	}

	interface IConfigParam {
		element?: Node,
		module?: string,
		resolve: any
	}
}
